apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpxdt-server
  labels:
    app: dpxdt
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "75%"
      maxSurge: 1
  selector:
    matchLabels:
      app: dpxdt
      tier: web-app
  template:
    metadata:
      name: dpxdt-server
      labels:
        app: dpxdt
        tier: web-app
    spec:
      imagePullSecrets:
        - name: docker-registry-service-account
      containers:
        - name: dpxdt-server
          image: g5search/dpxdt
          imagePullPolicy: Always
          command: [ "bundle", "exec", "puma", "-C", "config/puma.rb" ]
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi"
              cpu: "1000m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-password
