apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpxdt-server
  labels:
    app: dpxdt
  annotations:
    dalton.getg5.com/application: |-
      {
        "imageTags": [
          { "containerName": "dpxdt-server" }
        ]
      }
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "75%"
      maxSurge: 1
  selector:
    matchLabels:
      app: dpxdt
      tier: web-app
  template:
    metadata:
      name: dpxdt-server
      labels:
        app: dpxdt
        tier: web-app
    spec:
      imagePullSecrets:
        - name: docker-registry-service-account
      containers:
        - name: dpxdt-server
          image: g5search/dpxdt
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi"
              cpu: "1500m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: database-password
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: github-token
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: oauth2-proxy-client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: oauth2-proxy-client-secret 
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: oauth2-proxy-cookie-secret 
            - name: OAUTH2_PROXY_UPSTREAM
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: oauth2-proxy-upstream 
            - name: OAUTH2_PROXY_EMAIL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: third-party-tokens
                  key: oauth2-proxy-email-domain
            - name: G5_DPXDT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dpxdt
                  key: g5-dpxdt-api-key
            - name: INJECT_DIR
              value: /dpxdt-inject
        #- name: nginx-proxy
          #image: g5search/nginx-ssl-proxy
          #ports:
            #- name: http
              #containerPort: 80
          #env:
            #- name: TARGET_SERVICE
              #value: 127.0.0.1:5000
          #lifecycle:
            #preStop:
              #exec:
                #command: [ "nginx", "-s", "quit" ]
